[package]
name = "icon_enums"
version = "0.1.1"
edition = "2024"
authors = ["Remy Sedlak <reymsedlak@gmail.com>"]
description = "Rust library for creating an icon namespace for an asset directory"
license = "MIT"
repository = "https://github.com/remysedlak/icon_enums"
readme = "README.md"

[dependencies]
unicode-normalization = "0.1.24"
